# Workflow for Android CI debug build

name: Android CI

on:
  push:
  pull_request:
    branches: [ main, beta, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android Build
        run: ./gradlew assembleDebug