# Workflow for Android CI debug build

name: Android CI

on:
  push:
    branches: [ master, beta, dev ]
  pull_request:
    branches: [ master, beta, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleDebug"
