# Workflow for Android CI debug build

name: Android CI

on:
  push:
    branches: [ master, beta, dev ]
  pull_request:
    branches: [ master, beta, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with: './gradlew assembleDebug'