# Workflow for Android CI release

name: Publish to Sonatype

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Prepare environment
        env:
          SONATYPE_GPG_FILE_CONTENTS: ${{ secrets.SONATYPE_GPG_FILE_CONTENTS }}
          SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$SONATYPE_GPG_FILE_CONTENTS' | base64 -d > '$SONATYPE_GPG_FILE'"

      - name: Release build
        run: ./gradlew simplesettings:assembleRelease

      - name: Publish to MavenCentral
        run: ./gradlew simplesettings:publishReleasePublicationToSonatypeRepository -Plibrary_only --no-configure-on-demand --no-parallel dokkaHtml
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONATYPE_GPG_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
          SONATYPE_GPG_PASS: ${{ secrets.SONATYPE_GPG_PASS }}
          SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}